doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': 'src'
    organize_migrations: BY_YEAR_AND_MONTH
    storage:
        table_storage:
            table_name: 'migration_versions'
