sudo: false

language: php
php:
    - 7.1
    - 7.2

cache: apt

env:
    global:
        - SYMFONY_ENV=test

before_script:
  - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo | pecl install imagick
  - composer install -n -o

script:
  - ./vendor/bin/phpunit
