imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'
        cookie_secure: '%secure_cookies%'
        
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    
    form_themes:      
        - 'bootstrap_3_horizontal_layout.html.twig'
        - '@NinesUtilBundle/Form/fields.html.twig'
    paths:
        '%kernel.root_dir%/../src/Nines/UtilBundle/Resources/views': NinesUtilBundle
    exception_controller:  NinesUtilBundle:Error:showException
    globals:
        comment_service: "@feedback.comment"
        text_service: "@nines.util.text"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
        dql:
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year 
                DATE: DoctrineExtensions\Query\Mysql\Date
                STRTODATE: DoctrineExtensions\Query\Mysql\StrToDate                
            string_functions:
                MATCH_AGAINST: DoctrineExtensions\Query\Mysql\MatchAgainst
            numeric_functions:
                INT: Nines\NinesUtilBundle\Extensions\Doctrine\CastAsIntegerFunction
                RAND: Nines\NinesUtilBundle\Extensions\Doctrine\RandFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nines\UserBundle\Entity\User
    profile:
        form:
            type: Nines\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Nines\UserBundle\Form\PasswordType
            
ivory_ck_editor:
    input_sync: true
    default_config: btd_config
    configs:
        btd_config:
            toolbar: btd_toolbar
    toolbars:
        configs:
            btd_toolbar: 
                - [ Source, -, Cut, Copy, Paste, PasteText, PasteFromWord, -, Undo, Redo ]
                - [ Link, Unlink, Anchor, -, SpecialChar ]
                - [ Format, Styles, -, Bold, Italic, Strike, -, RemoveFormat, -, NumberedList, BulletedList, -, Indent, Outdent, -, Blockquote, -, JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock ]

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig

nines_feedback:
    default_status: submitted
    public_status: published
    commenting:
        blog_post:
            class: Nines\BlogBundle\Post
            route: post_show
        blog_page:
            class: Nines\BlogBundle\Page
            route: page_show

nines_blog:
    default_status: draft
    default_category: none

nines_user:
    permission_levels: [ ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN ]
        